seed_everything: 37
trainer:
  callbacks:
    - class_path: val_sample_plot_callback.ValSamplePlot
      init_args:
        directory: ./samples/mnist

  check_val_every_n_epoch: 1

  max_epochs: 100

data:
  batch_size: 256
